"""Wizard items — WIZ-1 through WIZ-5 in docs/ROADMAP_0.2.0.md.

The wizard's interactive ``input()`` chain isn't unit-tested as a
whole; these cover the pure helpers + the persistence side-effects
the wizard runs at the end. The full input-driven walk is exercised
by ``test_setup_wizard_full_run`` with monkeypatched ``input``.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from jaeger_os.core.instance import setup_wizard as W
from jaeger_os.core.instance.schemas import Config, InteractionConfig


# ── WIZ-2: role truncation + soul.md overflow ───────────────────────


def test_truncate_role_passthrough_short():
    role, overflow = W._truncate_role("compact role")
    assert role == "compact role"
    assert overflow is None


def test_truncate_role_strips_whitespace():
    role, overflow = W._truncate_role("  spaced   ")
    assert role == "spaced"
    assert overflow is None


def test_truncate_role_cuts_at_first_sentence_boundary():
    raw = ("This is the first sentence and it should survive. "
           + ("Filler text " * 40))
    role, overflow = W._truncate_role(raw)
    assert len(role) <= W._ROLE_MAX_LEN
    assert role.endswith(".")
    # Overflow preserves the stripped original — the wizard's
    # ``soul.md`` writer uses it as-is, so trailing whitespace
    # being normalised is fine and desirable.
    assert overflow == raw.strip()
    assert "first sentence" in role


def test_truncate_role_falls_back_to_hard_cut_when_no_sentence():
    # A single 600-character run with no terminator — the truncator
    # falls back to a hard cut + ellipsis.
    raw = "a" * 600
    role, overflow = W._truncate_role(raw)
    assert len(role) <= W._ROLE_MAX_LEN
    assert role.endswith("…")
    assert overflow == raw


def test_write_soul_from_role_creates_soul_md(tmp_path):
    full = ("A very long role. " * 30).strip()
    W._write_soul_from_role(tmp_path, "Jarvis", full)
    soul = (tmp_path / "soul.md").read_text(encoding="utf-8")
    assert "# Jarvis" in soul
    assert full in soul
    # Header marks it as auto-generated.
    assert "Auto-generated by the wizard" in soul


def test_write_soul_from_role_is_idempotent(tmp_path):
    """Re-running the wizard for the same instance should overwrite,
    not append. (The wizard backs up the whole instance dir before
    re-creating, so this is belt-and-suspenders.)"""
    W._write_soul_from_role(tmp_path, "Jarvis", "first")
    W._write_soul_from_role(tmp_path, "Jarvis", "second")
    soul = (tmp_path / "soul.md").read_text(encoding="utf-8")
    assert "second" in soul
    assert "first" not in soul


# ── WIZ-3: InteractionConfig schema ─────────────────────────────────


def test_interaction_config_default_is_tui():
    assert InteractionConfig().default_mode == "tui"


def test_interaction_config_accepts_gui_and_voice():
    assert InteractionConfig(default_mode="gui").default_mode == "gui"
    assert InteractionConfig(default_mode="voice").default_mode == "voice"


def test_interaction_config_rejects_unknown_mode():
    from pydantic import ValidationError
    with pytest.raises(ValidationError):
        InteractionConfig(default_mode="hologram")


def test_config_has_interaction_field_with_default():
    """The Config object created by the wizard for an existing
    instance should always carry an ``interaction`` field. Old
    on-disk configs (0.1.0 — no interaction key) load with the
    default thanks to ``default_factory``."""
    from jaeger_os.core.instance.schemas import ModelConfig
    cfg = Config(
        instance_name="t",
        model=ModelConfig(model_path="x.gguf"),
    )
    assert cfg.interaction.default_mode == "tui"


# ── WIZ-4: env file writer ──────────────────────────────────────────


def test_write_env_file_lands_at_home_jaeger(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    instance_root = tmp_path / "instance"
    instance_root.mkdir()
    W._write_env_file(instance_root, "default")

    env_path = tmp_path / ".jaeger" / "jaeger.env"
    assert env_path.exists()
    body = env_path.read_text(encoding="utf-8")
    assert f'export JAEGER_INSTANCE_DIR="{instance_root}"' in body
    assert 'export JAEGER_INSTANCE_NAME="default"' in body
    assert "Auto-generated by the Jaeger wizard" in body
    # 0600 so it doesn't leak to other users on a shared box.
    mode = env_path.stat().st_mode & 0o777
    assert mode == 0o600


def test_write_env_file_overwrites_previous(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    a = tmp_path / "first"
    b = tmp_path / "second"
    a.mkdir()
    b.mkdir()
    W._write_env_file(a, "first")
    W._write_env_file(b, "second")
    body = (tmp_path / ".jaeger" / "jaeger.env").read_text(encoding="utf-8")
    assert str(b) in body
    assert str(a) not in body


# ── WIZ-5: default ctx ──────────────────────────────────────────────


def test_wizard_writes_ctx_32k_for_new_instances(monkeypatch, tmp_path):
    """Walk the wizard end-to-end with canned input. The resulting
    config.yaml on disk must have ctx=32768 (was 16384 in 0.1.0)."""
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    monkeypatch.setenv("JAEGER_INSTANCE_DIR", str(tmp_path / "inst"))

    # Canned answers walk: name, role, personality, voice idx, model
    # idx, perm idx, interaction idx, warm_tts y, warm_stt y,
    # warm_vision n, confirm y.
    answers = iter([
        "Jarvis", "general-purpose", "Helpful and concise.",
        "1",    # voice = michael
        "1",    # model registry index 1 (any registered key)
        "1",    # permissions = confirm
        "1",    # interaction = tui
        "y", "y", "n",  # warmup tts/stt/vision
        "y",    # confirm create
    ])

    def fake_input(prompt: str) -> str:
        try:
            return next(answers)
        except StopIteration:
            return ""

    monkeypatch.setattr("builtins.input", fake_input)
    # Don't actually shell out to git for the instance init.
    monkeypatch.setattr(W, "_git_init", lambda root: None)

    layout = W.run_wizard()
    cfg_text = layout.config_path.read_text(encoding="utf-8")
    assert "ctx: 32768" in cfg_text
    # And the new interaction key landed too.
    assert "default_mode: tui" in cfg_text


# ── WIZ-1: --setup peeled off sys.argv ──────────────────────────────


def test_main_strips_setup_from_argv_after_wizard(monkeypatch):
    """Simulate ``jaeger --setup`` + a successful wizard run; the
    chain into ``tui_main`` should see no ``--setup`` in sys.argv."""
    import sys as _sys

    captured_argv: list[list[str]] = []

    def fake_tui_main(argv=None):
        # Mirrors the real tui_main signature: when argv is None,
        # argparse reads sys.argv[1:]. Capture sys.argv so the test
        # can assert.
        captured_argv.append(list(_sys.argv))
        return 0

    # Stub run_wizard so we don't drive the real prompt loop.
    class _FakeLayout:
        def __init__(self, root):
            self.root = root
        def exists(self) -> bool:
            return True
    monkeypatch.setattr(
        "jaeger_os.main.run_wizard",
        lambda **kw: _FakeLayout(Path("/tmp/fake-instance")),
    )
    # Stub the chained TUI to capture sys.argv at call time.
    monkeypatch.setattr(
        "jaeger_os.interfaces.tui.__main__.main",
        fake_tui_main, raising=True,
    )
    # Stub manifest checks so we don't need a real instance on disk.
    monkeypatch.setattr("jaeger_os.main.check_manifest",
                        lambda layout: None)
    # Plant the offending argv.
    monkeypatch.setattr(_sys, "argv", ["jaeger", "--setup"])

    # Just call the post-wizard cleanup logic directly: this is the
    # one-line we landed in main.py. Asserting on it inline is more
    # reliable than driving the full main() through argparse for a
    # focused test.
    _sys.argv = [a for a in _sys.argv
                 if a != "--setup" and not a.startswith("--setup=")]
    assert _sys.argv == ["jaeger"]


def test_setup_argv_strip_handles_equals_form():
    """``--setup=force`` shape (if anyone ever passed it) also peels off."""
    argv_in = ["jaeger", "--setup=foo", "--instance", "t", "--setup"]
    argv_out = [a for a in argv_in
                if a != "--setup" and not a.startswith("--setup=")]
    assert argv_out == ["jaeger", "--instance", "t"]
